{% set name = "slack-sdk" %}
{% set version = "3.20.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/slack_sdk-{{ version }}.tar.gz
  sha256: 0ba2eca9f0aeb66cc893a768e7ad2cdd74260c394b9b51666d4b665664d0cadd

build:
  number: 0

outputs:
  - name: slack-sdk
    build:
      noarch: python
      script: python -m pip install . -vv
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - python >=3.6
    test:
      imports:
        - slack_sdk
        - slack_sdk.web
        - slack_sdk.webhook
        - slack_sdk.signature
        - slack_sdk.socket_mode
        - slack_sdk.audit_logs
        - slack_sdk.scim
        - slack_sdk.oauth
        - slack_sdk.models
        # The old RTM API has a dependency on aiohttp
        # - slack_sdk.rtm
        - slack_sdk.rtm_v2
      commands:
        - pip check
        - conda install -y aiohttp
        - python -c "import slack_sdk.rtm"
      requires:
        - pip
  - name: slack_sdk
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}
    test:
      imports:
        - slack_sdk

about:
  home: https://github.com/slackapi/python-slack-sdk
  summary: The Slack API Platform SDK for Python
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/slackapi/python-slack-sdk
  doc_url: https://github.com/slackapi/python-slack-sdk

extra:
  recipe-maintainers:
    - xylar
    - maresb
